services:
  ros2:
    build:
      context: .
      args:
        USERNAME: ${HOST_USER}
        USER_UID: ${HOST_UID}
        USER_GID: ${HOST_GID}

    container_name: ros2-lyrical

    network_mode: host

    environment:
      DISPLAY: ${DISPLAY}
      QT_QPA_PLATFORM: xcb
      TERM: xterm-256color
    
    devices:
      - /dev/dri:/dev/dri

    group_add:
      - "${VIDEO_GID}"
      - "${RENDER_GID}"

    volumes:
      - ${HOME}/ros2_ws/src:/home/${HOST_USER}/ros2_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

    stdin_open: true
    tty: true

    command: sleep infinity
